[package]
name = "run-deck"
version = "0.1.0"
description = "A minimal Tauri App"
authors = ["you"]
edition = "2024"

[lib]
name = "run_deck_lib"
crate-type = ["cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }  # 必须：Tauri 构建工具

[dependencies]
tauri = { version = "2", features = [] }  # 核心 Tauri 运行时
serde = { workspace = true }
serde_json = { workspace = true }
tauri-plugin-opener = "2"

[lints]
workspace = true
