/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    CheckInRecords: typeof import('./src/components/worktime-dashboard/CheckInRecords.vue')['default']
    DashboardOverview: typeof import('./src/components/worktime-dashboard/DashboardOverview.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    GeneralSettings: typeof import('./src/components/config/GeneralSettings.vue')['default']
    LabelCanvas: typeof import('./src/components/label/LabelCanvas.vue')['default']
    LabelInfoPanel: typeof import('./src/components/label/LabelInfoPanel.vue')['default']
    LabelModePanel: typeof import('./src/components/shared/LabelModePanel.vue')['default']
    LabelNameDialogHandler: typeof import('./src/components/label/LabelNameDialogHandler.vue')['default']
    LabelPickerDialog: typeof import('./src/components/label/LabelPickerDialog.vue')['default']
    LabelRawCanvas: typeof import('./src/components/label-raw/LabelRawCanvas.vue')['default']
    LabelRawKeyframePanel: typeof import('./src/components/label-raw/LabelRawKeyframePanel.vue')['default']
    LabelRawNameDialogHandler: typeof import('./src/components/label-raw/LabelRawNameDialogHandler.vue')['default']
    LabelRawObjectSelectPopup: typeof import('./src/components/label-raw/LabelRawObjectSelectPopup.vue')['default']
    LabelRawSliceSlider: typeof import('./src/components/label-raw/LabelRawSliceSlider.vue')['default']
    LabelRawToolbar: typeof import('./src/components/label-raw/LabelRawToolbar.vue')['default']
    LabelSettingsButton: typeof import('./src/components/shared/LabelSettingsButton.vue')['default']
    LabelSettingsDrawer: typeof import('./src/components/label/LabelSettingsDrawer.vue')['default']
    LabelToolbar: typeof import('./src/components/label/LabelToolbar.vue')['default']
    LabelToolPanel: typeof import('./src/components/shared/LabelToolPanel.vue')['default']
    McpServerDetail: typeof import('./src/components/mcp-panel/McpServerDetail.vue')['default']
    McpServerForm: typeof import('./src/components/config/McpServerForm.vue')['default']
    McpServerList: typeof import('./src/components/config/McpServerList.vue')['default']
    McpServerSidebar: typeof import('./src/components/mcp-panel/McpServerSidebar.vue')['default']
    ObjectSelectDialog: typeof import('./src/components/label/ObjectSelectDialog.vue')['default']
    ObjectSelectPopup: typeof import('./src/components/label/ObjectSelectPopup.vue')['default']
    PageLayout: typeof import('./src/components/layout/PageLayout.vue')['default']
    PredictedWorktime: typeof import('./src/components/worktime-dashboard/PredictedWorktime.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./src/components/worktime-dashboard/StatCard.vue')['default']
    TitleBar: typeof import('./src/components/layout/TitleBar.vue')['default']
    WorktimeCalendar: typeof import('./src/components/worktime-dashboard/WorktimeCalendar.vue')['default']
    WorktimeChart: typeof import('./src/components/worktime-dashboard/WorktimeChart.vue')['default']
    WorktimeEntryDialog: typeof import('./src/components/worktime-dashboard/WorktimeEntryDialog.vue')['default']
    WorktimeSettings: typeof import('./src/components/worktime-dashboard/WorktimeSettings.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
