export const LABELS = {
  nav: {
    overview: '导航',
    config: '配置',
    label: '标注',
    mcpPanel: 'MCP 面板',
    general: '通用',
    mcpServers: 'MCP 服务器',
  },
  theme: {
    light: '浅色',
    dark: '深色',
    toggle: '切换主题',
    mode: '主题模式',
  },
  settings: {
    title: '通用设置',
    logLevel: '日志级别',
    homeRoute: '首页路由',
    shellType: 'Shell 类型',
  },
  logLevel: {
    error: '错误',
    warn: '警告',
    info: '信息',
    debug: '调试',
    trace: '追踪',
  },
  shell: {
    auto: '自动',
  },
  mcpServer: {
    type: '服务器类型',
    typeLocal: '本地（stdio）',
    typeRemote: '远程（HTTP）',
    typeLocalFull: '本地服务器（stdio）',
    typeRemoteFull: '远程服务器（HTTP）',
    name: '名称',
    command: '启动命令（每行一个参数）',
    env: '环境变量（每行 KEY=value）',
    timeout: '超时（毫秒，可选）',
    url: 'URL',
    headers: '请求头（每行 KEY=value）',
    enabled: '启用',
    disabled: '已禁用',
    status: {
      starting: '启动中',
      running: '运行中',
      stopped: '已停止',
      failed: '失败',
      unknown: '未知',
    },
  },
  mcpDetail: {
    tools: '工具',
    prompts: '提示',
    resources: '资源',
    description: '描述',
    params: '参数',
    mimeType: 'MIME 类型',
    noTools: '暂无工具',
    noPrompts: '暂无提示',
    noResources: '暂无资源',
    selectServer: '请选择一个 MCP 服务器查看详情',
    serverNotFound: '服务器不存在',
    serverDisabled: '服务器已禁用',
    serverDisabledDesc: '该服务器已在配置中禁用',
    serverFailed: '服务器启动失败',
    serverNotRunning: '服务器未运行',
    fetchError: '获取服务器数据失败',
    unknownError: '未知错误',
  },
  mcpForm: {
    addTitle: '添加服务器',
    editTitle: (name: string) => `编辑 ${name}`,
    duplicateName: '服务器名称已存在',
    added: (name: string) => `已添加服务器「${name}」`,
    updated: (name: string) => `已更新服务器「${name}」`,
    deleted: (name: string) => `已删除服务器「${name}」`,
  },
  mcpList: {
    title: 'MCP 服务器',
    add: '添加',
    addServer: '添加服务器',
    emptyTitle: '暂无 MCP 服务器',
    emptyDesc: '点击下方按钮添加第一个 MCP 服务器',
    deleteTitle: '确认删除',
    deleteDesc: (name: string) => `确定要删除服务器「${name}」吗？此操作不可撤销。`,
    selectTypeTitle: '选择服务器类型',
    selectTypeDesc: '选择要添加的 MCP 服务器类型',
  },
  overview: {
    title: '导航',
    configDesc: '日志级别、首页、主题、MCP 服务器管理',
    mcpPanelDesc: '查看 MCP 服务器工具、提示、资源',
  },
  common: {
    save: '保存',
    cancel: '取消',
    delete: '删除',
    add: '添加',
  },
  validation: {
    nameRequired: '名称不能为空',
    commandRequired: '启动命令不能为空',
    urlInvalid: 'URL 格式无效',
    configSyncFailed: '配置同步失败，已回滚',
  },
} as const;
