export const LABELS = {
  nav: {
    overview: '导航',
    config: '配置',
    label: '标注',
    mcpPanel: 'MCP 面板',
    general: '通用',
    mcpServers: 'MCP 服务器',
    logs: '日志',
  },
  theme: {
    light: '浅色',
    dark: '深色',
    toggle: '切换主题',
    mode: '主题模式',
  },
  settings: {
    title: '通用设置',
    logLevel: '日志级别',
    homeRoute: '首页路由',
    shellType: 'Shell 类型',
    logTitle: '日志配置',
    logMaxSizeMb: '单文件大小 (MB)',
    logKeepFiles: '保留文件数',
    logRetentionDays: '保留天数',
    logRestartHint: '轮转参数改动将在下次启动生效',
    openLogsDir: '打开日志目录',
    cleanupLogs: '立即清理',
    cleanupDone: (n: number) => `已删除 ${n} 个日志文件`,
    cleanupFailed: '日志清理失败',
    openDirFailed: '打开日志目录失败',
  },
  logLevel: {
    error: '错误',
    warn: '警告',
    info: '信息',
    debug: '调试',
    trace: '追踪',
  },
  shell: {
    auto: '自动',
  },
  mcpServer: {
    type: '服务器类型',
    typeLocal: '本地（stdio）',
    typeRemote: '远程（HTTP）',
    typeLocalFull: '本地服务器（stdio）',
    typeRemoteFull: '远程服务器（HTTP）',
    name: '名称',
    command: '启动命令（每行一个参数）',
    env: '环境变量（每行 KEY=value）',
    timeout: '超时（毫秒，可选）',
    url: 'URL',
    headers: '请求头（每行 KEY=value）',
    enabled: '启用',
    disabled: '已禁用',
    status: {
      starting: '启动中',
      running: '运行中',
      stopped: '已停止',
      failed: '失败',
      unknown: '未知',
    },
  },
  mcpDetail: {
    tools: '工具',
    prompts: '提示',
    resources: '资源',
    description: '描述',
    params: '参数',
    mimeType: 'MIME 类型',
    noTools: '暂无工具',
    noPrompts: '暂无提示',
    noResources: '暂无资源',
    selectServer: '请选择一个 MCP 服务器查看详情',
    serverNotFound: '服务器不存在',
    serverDisabled: '服务器已禁用',
    serverDisabledDesc: '该服务器已在配置中禁用',
    serverFailed: '服务器启动失败',
    serverNotRunning: '服务器未运行',
    fetchError: '获取服务器数据失败',
    unknownError: '未知错误',
  },
  mcpForm: {
    addTitle: '添加服务器',
    editTitle: (name: string) => `编辑 ${name}`,
    duplicateName: '服务器名称已存在',
    added: (name: string) => `已添加服务器「${name}」`,
    updated: (name: string) => `已更新服务器「${name}」`,
    deleted: (name: string) => `已删除服务器「${name}」`,
  },
  mcpList: {
    title: 'MCP 服务器',
    add: '添加',
    addServer: '添加服务器',
    emptyTitle: '暂无 MCP 服务器',
    emptyDesc: '点击下方按钮添加第一个 MCP 服务器',
    deleteTitle: '确认删除',
    deleteDesc: (name: string) => `确定要删除服务器「${name}」吗？此操作不可撤销。`,
    selectTypeTitle: '选择服务器类型',
    selectTypeDesc: '选择要添加的 MCP 服务器类型',
  },
  overview: {
    title: '导航',
    configDesc: '首页、主题、MCP 服务器管理',
    mcpPanelDesc: '查看 MCP 服务器工具、提示、资源',
    labelDesc: '3D 体数据打标：切片浏览、点/框标注',
  },
  labelSettings: {
    title: '标签定义',
    add: '新增标签',
    name: '名称',
    color: '颜色',
    order: '顺序',
    subLabels: '子标签',
    addSubLabel: '添加子标签',
    deleteConfirmTitle: '删除标签',
    deleteConfirmDesc: (name: string) => `确定要删除标签「${name}」吗？此操作不可撤销。`,
    nameRequired: '名称不能为空',
    added: (name: string) => `已添加标签「${name}」`,
    updated: (name: string) => `已更新标签「${name}」`,
    deleted: (name: string) => `已删除标签「${name}」`,
    noLabels: '暂无标签，点击「新增标签」创建',
  },
  label3d: {
    open: '打开 Raw',
    openButton: '打开',
    selectRawFile: '选择 Raw 文件',
    rawData: 'Raw 数据',
    volumeConfig: 'Volume 配置',
    volumeOpened: '已打开 volume',
    reset: '重置',
    fitImage: '适应图像',
    save: '保存',
    saveShortcut: '保存 (Ctrl+S)',
    manageLabels: '标签管理',
    select: '选择',
    move: '移动',
    selectLabel: '选择标签',
    newLabel: '新建标签',
    positivePoint: '正点',
    negativePoint: '负点',
    box: '框',
    delete: '删除',
    sliceLabel: (index: number) => `Slice ${index}`,
    sliceCount: (count: number) => `(${count})`,
    dirtyTitle: '未保存的修改',
    dirtyDesc: '当前切片有未保存的标注，切换前要保存吗？',
    discard: '不保存',
    slice: '切片',
    slices: 'Slices',
    sliceCounter: (current: number, total: number) => `Slice ${current} / ${total}`,
    unknownLabel: 'Unknown',
    allSlices: '全部切片',
    annotatedOnly: '仅有标注',
    noAnnotations: '无标注',
    setVisualBox: '设为 Visual Box',
    reassign: '转移对象',
    deleteAnnotation: '删除标注',
    coordinate: '坐标',
    noObjects: '暂无对象',
    noLabels: '暂无标签，请先到标签管理创建',
    sliceLoadFailed: (index: number) => `切片 ${index} 加载失败`,
    openFailed: (e: unknown) => `打开失败: ${e}`,
    sliceCleared: (index: number) => `切片 ${index} 标注已清空`,
    sliceSaved: (index: number) => `切片 ${index} 已保存`,
    saveFailed: (e: unknown) => `保存失败: ${e}`,
    pointMustBeInBox: '点必须在边界框内',
  },
  logViewer: {
    title: '实时日志',
    pause: '暂停',
    resume: '恢复',
    clear: '清空',
    export: '导出',
    searchPlaceholder: '搜索（空格分隔，多词 AND）',
    levelAll: '全部级别',
    empty: '暂无日志',
    exportFailed: '导出失败',
  },
  common: {
    save: '保存',
    cancel: '取消',
    delete: '删除',
    add: '添加',
  },
  validation: {
    nameRequired: '名称不能为空',
    commandRequired: '启动命令不能为空',
    urlInvalid: 'URL 格式无效',
    configSyncFailed: '配置同步失败，已回滚',
  },
} as const;
