[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
toasty = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
