/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type { _ExtractParamParserType } from 'vue-router/experimental';

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {};
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap;
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap;
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>, never>;
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      never
    >;
    '/config': RouteRecordInfo<
      '/config',
      '/config',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/label': RouteRecordInfo<
      '/label',
      '/label',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/label-raw': RouteRecordInfo<
      '/label-raw',
      '/label-raw',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/mcp-panel': RouteRecordInfo<
      '/mcp-panel',
      '/mcp-panel',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/overview': RouteRecordInfo<
      '/overview',
      '/overview',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/worktime-dashboard': RouteRecordInfo<
      '/worktime-dashboard',
      '/worktime-dashboard',
      Record<never, never>,
      Record<never, never>,
      never
    >;
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/';
      views: never;
      pathParamNames: never;
    };
    'src/pages/[...path].vue': {
      routes: '/[...path]';
      views: never;
      pathParamNames: 'path';
    };
    'src/pages/config.vue': {
      routes: '/config';
      views: never;
      pathParamNames: never;
    };
    'src/pages/label.vue': {
      routes: '/label';
      views: never;
      pathParamNames: never;
    };
    'src/pages/label-raw.vue': {
      routes: '/label-raw';
      views: never;
      pathParamNames: never;
    };
    'src/pages/mcp-panel.vue': {
      routes: '/mcp-panel';
      views: never;
      pathParamNames: never;
    };
    'src/pages/overview.vue': {
      routes: '/overview';
      views: never;
      pathParamNames: never;
    };
    'src/pages/worktime-dashboard.vue': {
      routes: '/worktime-dashboard';
      views: never;
      pathParamNames: never;
    };
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info> ? Info['routes'] : keyof RouteNamedMap;
}

export {};
