/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as LabelRouteImport } from './routes/label'
import { Route as LabelSettingsRouteImport } from './routes/label-settings'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as McpPanelRouteImport } from './routes/mcp-panel'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as TasksRouteImport } from './routes/tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelRoute = LabelRouteImport.update({
  id: '/label',
  path: '/label',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelSettingsRoute = LabelSettingsRouteImport.update({
  id: '/label-settings',
  path: '/label-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const McpPanelRoute = McpPanelRouteImport.update({
  id: '/mcp-panel',
  path: '/mcp-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/label': typeof LabelRoute
  '/label-settings': typeof LabelSettingsRoute
  '/logs': typeof LogsRoute
  '/mcp-panel': typeof McpPanelRoute
  '/overview': typeof OverviewRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/label': typeof LabelRoute
  '/label-settings': typeof LabelSettingsRoute
  '/logs': typeof LogsRoute
  '/mcp-panel': typeof McpPanelRoute
  '/overview': typeof OverviewRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/label': typeof LabelRoute
  '/label-settings': typeof LabelSettingsRoute
  '/logs': typeof LogsRoute
  '/mcp-panel': typeof McpPanelRoute
  '/overview': typeof OverviewRoute
  '/tasks': typeof TasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config'
    | '/label'
    | '/label-settings'
    | '/logs'
    | '/mcp-panel'
    | '/overview'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/config'
    | '/label'
    | '/label-settings'
    | '/logs'
    | '/mcp-panel'
    | '/overview'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/config'
    | '/label'
    | '/label-settings'
    | '/logs'
    | '/mcp-panel'
    | '/overview'
    | '/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigRoute: typeof ConfigRoute
  LabelRoute: typeof LabelRoute
  LabelSettingsRoute: typeof LabelSettingsRoute
  LogsRoute: typeof LogsRoute
  McpPanelRoute: typeof McpPanelRoute
  OverviewRoute: typeof OverviewRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/label': {
      id: '/label'
      path: '/label'
      fullPath: '/label'
      preLoaderRoute: typeof LabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/label-settings': {
      id: '/label-settings'
      path: '/label-settings'
      fullPath: '/label-settings'
      preLoaderRoute: typeof LabelSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp-panel': {
      id: '/mcp-panel'
      path: '/mcp-panel'
      fullPath: '/mcp-panel'
      preLoaderRoute: typeof McpPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigRoute: ConfigRoute,
  LabelRoute: LabelRoute,
  LabelSettingsRoute: LabelSettingsRoute,
  LogsRoute: LogsRoute,
  McpPanelRoute: McpPanelRoute,
  OverviewRoute: OverviewRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
